### ISSUE TITLE
1.12 Upgrade Guide

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jqueryui.com#132]
There are a few things left for the upgrade guide:

* [ ] Document all effects rewrite [#10599](http://bugs.jqueryui.com/ticket/10599)
* [x] Spinner deprecated `_buttonHtml()` and `uiSpinnerHtml()` methods [#11097](http://bugs.jqueryui.com/ticket/11097)
* [x] New APIs
  * [x] form-reset-mixin [#12638](http://bugs.jqueryui.com/ticket/12638)
  * [x] slider index available in event handlers [#7630](http://bugs.jqueryui.com/ticket/7630)
  * [x] tooltip elements as content [#9278](http://bugs.jqueryui.com/ticket/9278)
  * [x] widget mixins [#12601](http://bugs.jqueryui.com/ticket/12601)
* [x] Remove the section about `$.ui.intersect()` being removed.
  * This was restored, but I don't want to update the upgrade guide until we release a version that has it restored.
